import React,{useEffect,useState} from 'react';
import {ArrowRight,BarChart3,Check,Clock,Coffee,MoreHorizontal,Package,Plus,RefreshCw,Save,ShieldCheck,ShoppingBag,Trash2,Wallet} from 'lucide-react';
import './admin.css';
import './admin-extra.css';

type Product={id:string,name:string,category:string,icon?:string,quick:boolean,active:boolean,variants:{id:string,name:string,price:number,volumeMl?:number,active:boolean}[]};
type Catalog={products:Product[],categories:{name:string,icon?:string}[],activeCount:number,hiddenCount:number};
type Order={id:string,number:number,totalAmount:number,createdAt:string,status:string,comment?:string,payments:{method:string,amount:number}[],items:{name:string,variant:string,quantity:number,totalPrice:number,modifiers:{name:string,quantity:number}[]}[]};
type User={id:string,telegramId:number,firstName:string,lastName?:string,username?:string,role:string,isActive:boolean,lastLoginAt?:string};
type Shift={id:string,businessDate:string,openedAt:string,openingCash:number,expectedClosingCash:number,actualClosingCash?:number,cashDifference?:number,status:string,user:string};
type Overview={revenue:number,ordersCount:number,cash:number,card:number,openShifts:number,usersCount:number};
type AdminAnalytics={revenue:number,ordersCount:number,cash:number,card:number,positions:{name:string,quantity:number}[]};
const api=async<T,>(path:string,options:RequestInit={}):Promise<T>=>{const tg=(window as any).Telegram?.WebApp;const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(options.headers||{})}});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.message||'Не удалось выполнить операцию')}return r.json()};
const money=(v=0)=>new Intl.NumberFormat('uk-UA',{style:'currency',currency:'UAH',maximumFractionDigits:2}).format(v);const today=()=>new Date().toISOString().slice(0,10);const dateTime=(v:string)=>new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});

export default function FullAdminApp({onBarista}:{onBarista:()=>void}){
 const [section,setSection]=useState<'dashboard'|'orders'|'shifts'|'users'|'catalog'|'analytics'|'settings'>('dashboard');const [date,setDate]=useState(today);const [userId,setUserId]=useState('');const [status,setStatus]=useState('');const [overview,setOverview]=useState<Overview|null>(null);const [analytics,setAnalytics]=useState<AdminAnalytics|null>(null);const [orders,setOrders]=useState<Order[]>([]);const [shifts,setShifts]=useState<Shift[]>([]);const [users,setUsers]=useState<User[]>([]);const [catalog,setCatalog]=useState<Catalog|null>(null);const [busy,setBusy]=useState(false);const [toast,setToast]=useState('');const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState<any>({name:'',category:'Кофе',icon:'☕',variantName:'Стандарт',price:'',quick:false,active:true});
 const load=async()=>{setBusy(true);try{const suffix=userId?'&userId='+userId:'';const st=status?'&status='+status:'';const [o,a,ord,sh,u,c]=await Promise.all([api<Overview>('/api/admin/overview?date='+date),api<AdminAnalytics>('/api/admin/analytics?from='+date+'&to='+date+(userId?'&userId='+userId:'')),api<Order[]>('/api/admin/orders?date='+date+suffix+st),api<Shift[]>('/api/admin/shifts?date='+date+suffix),api<User[]>('/api/admin/users'),api<Catalog>('/api/admin/catalog')]);setOverview(o);setAnalytics(a);setOrders(ord);setShifts(sh);setUsers(u);setCatalog(c)}catch(e:any){setToast(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[date,userId,status]);
 const act=async(path:string,options:RequestInit={})=>{setBusy(true);try{await api(path,options);await load()}catch(e:any){setToast(e.message)}finally{setBusy(false)}};
 const editProduct=(p:Product)=>{const v=p.variants[0];setEditing(p.id);setDraft({name:p.name,category:p.category,icon:p.icon||'☕',variantName:v?.name||'Стандарт',price:String(v?.price||0),quick:p.quick,active:p.active,variantId:v?.id})};
 const saveProduct=async(id?:string)=>{const price=Number(String(draft.price).replace(',','.'));if(!draft.name||!draft.category||!Number.isFinite(price)){setToast('Заполните название, категорию и цену');return}await act(id?'/api/admin/products/'+id:'/api/admin/products',{method:id?'PUT':'POST',body:JSON.stringify({...draft,price,volumeMl:null,variantId:draft.variantId||null})});setEditing(null);setDraft({name:'',category:'Кофе',icon:'☕',variantName:'Стандарт',price:'',quick:false,active:true})};
 const label=(s:string)=>s==='Completed'?'Выполнен':s==='Cancelled'?'Удалён':s;
 return <div className="app admin-shell"><header><div className="brand"><div className="logo"><ShieldCheck size={22}/></div><div><strong>Панель администратора</strong><small>Полный доступ</small></div></div><button className="avatar" onClick={()=>setSection('settings')}>A</button></header>{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}<main>
 {section==='dashboard'&&<><div className="title-row"><div><small>Общая статистика</small><h1>Дашборд</h1></div><button className="icon-button" onClick={load}><RefreshCw/></button></div><label>Дата<input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label><div className="hero"><span>Выручка за день</span><b>{money(overview?.revenue)}</b><small>{overview?.ordersCount||0} заказов · открытых смен: {overview?.openShifts||0}</small></div><div className="stats"><div><span>Наличные</span><b>{money(overview?.cash)}</b></div><div><span>Карта</span><b>{money(overview?.card)}</b></div><div><span>Сотрудники</span><b>{overview?.usersCount||0}</b></div></div><div className="admin-analytics-grid"><div><span>Средний чек</span><b>{money(overview?.ordersCount?(overview.revenue/overview.ordersCount):0)}</b></div><div><span>Позиций продано</span><b>{analytics?.positions.reduce((n,p)=>n+p.quantity,0)||0}</b></div></div><h2 className="section-title">Популярные позиции</h2><section className="chart-card">{analytics?.positions.map(p=><div className="admin-position-row" key={p.name}><span>{p.name}</span><small>{p.quantity} шт.</small></div>)}</section><div className="admin-dashboard-actions"><button className="admin-entry" onClick={()=>setSection('orders')}><span><ShoppingBag/><b>Заказы</b><small>Просмотр и управление</small></span><ArrowRight/></button><button className="admin-entry" onClick={()=>setSection('shifts')}><span><Clock/><b>Смены</b><small>Касса и расхождения</small></span><ArrowRight/></button><button className="admin-entry" onClick={()=>setSection('users')}><span><ShieldCheck/><b>Сотрудники</b><small>Роли и доступ</small></span><ArrowRight/></button><button className="admin-entry" onClick={()=>setSection('catalog')}><span><Package/><b>Меню и цены</b><small>{catalog?.activeCount||0} позиций в продаже</small></span><ArrowRight/></button></div></>}
 {section==='orders'&&<><div className="title-row"><div><small>Все сотрудники</small><h1>Заказы</h1></div><button className="icon-button" onClick={load}><RefreshCw/></button></div><div className="admin-filters"><label>Дата<input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label><label>Сотрудник<select value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Все сотрудники</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName}</option>)}</select></label><label>Статус<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все статусы</option><option value="Completed">Выполнен</option><option value="Cancelled">Удалён</option></select></label></div>{orders.map(o=><article className="order-card" key={o.id}><div className="order-top"><div><b>Заказ #{o.number}</b><small>{dateTime(o.createdAt)}</small></div><strong>{money(o.totalAmount)}</strong></div>{o.comment&&<div className="order-edited-note">✎ {o.comment}</div>}<div className="order-positions">{o.items.map((i,n)=><div className="order-position" key={n}><b>{i.name} × {i.quantity}</b><small>{i.variant} · {money(i.totalPrice)}</small>{i.modifiers?.length>0&&<div className="order-modifiers">{i.modifiers.map((m,j)=><span key={j}>{m.name}{m.quantity>1?' ×'+m.quantity:''}</span>)}</div>}</div>)}</div><div className="order-bottom"><small>{label(o.status)} · {o.payments.map(p=>p.method==='Cash'?'Наличные':'Карта').join(' + ')}</small>{o.status==='Completed'&&<button className="soft-danger" onClick={()=>act('/api/orders/'+o.id,{method:'DELETE'})} disabled={busy}><Trash2 size={15}/> Удалить</button>}</div></article>)}</>}
 {section==='shifts'&&<><div className="title-row"><div><small>Все сотрудники</small><h1>Смены</h1></div><button className="icon-button" onClick={load}><RefreshCw/></button></div><div className="admin-filters"><label>Дата<input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label><label>Сотрудник<select value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Все сотрудники</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName}</option>)}</select></label></div>{shifts.map(s=><article className="order-card" key={s.id}><div className="order-top"><div><b>{s.user}</b><small>{s.businessDate} · {s.status==='Open'?'Открыта':'Закрыта'}</small></div><strong>{money(s.expectedClosingCash)}</strong></div><div className="shift-details"><span>Старт: {money(s.openingCash)}</span><span>Факт: {s.actualClosingCash==null?'—':money(s.actualClosingCash)}</span><span>Разница: {s.cashDifference==null?'—':money(s.cashDifference)}</span></div></article>)}</>}
 {section==='users'&&<><div className="title-row"><div><small>Доступ и роли</small><h1>Сотрудники</h1></div><button className="icon-button" onClick={load}><RefreshCw/></button></div>{users.map(u=><article className="order-card" key={u.id}><div className="order-top"><div><b>{u.firstName} {u.lastName||''}</b><small>{u.username?'@'+u.username:'Telegram ID: '+u.telegramId}</small></div><strong>{u.role==='Admin'?'Администратор':'Бариста'}</strong></div><div className="order-bottom"><small>{u.isActive?'Активен':'Заблокирован'}</small><div className="admin-user-actions"><select value={u.role} onChange={e=>act('/api/admin/users/'+u.id,{method:'PUT',body:JSON.stringify({isActive:u.isActive,role:e.target.value})})} disabled={busy}><option value="Barista">Бариста</option><option value="Admin">Администратор</option></select><button className={u.isActive?'soft-danger':'restore'} onClick={()=>act('/api/admin/users/'+u.id,{method:'PUT',body:JSON.stringify({isActive:!u.isActive,role:u.role})})} disabled={busy}>{u.isActive?'Заблокировать':'Разблокировать'}</button></div></div></article>)}</>}
 {section==='catalog'&&<><div className="title-row"><div><small>Категории, позиции и цены</small><h1>Меню</h1></div><button className="icon-button" onClick={load}><RefreshCw/></button></div><details className="add-product" open={editing===null}><summary><Plus size={17}/> Добавить позицию</summary><div className="product-form"><label>Название<input value={editing===null?draft.name:''} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="form-grid"><label>Категория<input list="admin-categories" value={editing===null?draft.category:''} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Иконка<input value={editing===null?draft.icon:''} onChange={e=>setDraft({...draft,icon:e.target.value})}/></label></div><div className="form-grid"><label>Вариант<input value={editing===null?draft.variantName:''} onChange={e=>setDraft({...draft,variantName:e.target.value})}/></label><label>Цена<input value={editing===null?draft.price:''} onChange={e=>setDraft({...draft,price:e.target.value})}/></label></div><button className="primary" onClick={()=>saveProduct()} disabled={busy}><Plus size={17}/> Добавить</button></div></details><datalist id="admin-categories">{catalog?.categories.map(c=><option key={c.name} value={c.name}/>)}</datalist>{catalog?.products.map(p=><article className="admin-product" key={p.id}>{editing===p.id?<div className="product-form compact"><label>Название<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="form-grid"><label>Категория<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Цена<input value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></label></div><div className="admin-actions"><button className="secondary" onClick={()=>setEditing(null)}>Отмена</button><button className="primary" onClick={()=>saveProduct(p.id)} disabled={busy}><Save size={16}/> Сохранить</button></div></div>:<><div className="admin-product-head"><div><b>{p.icon||'☕'} {p.name}</b><small>{p.category} · {money(p.variants[0]?.price)}</small></div><span>{p.active?'В продаже':'Скрыто'}</span></div><div className="admin-actions"><button className="secondary" onClick={()=>editProduct(p)}>Редактировать</button>{p.active?<button className="soft-danger" onClick={()=>act('/api/admin/products/'+p.id,{method:'DELETE'})}>Скрыть</button>:<button className="restore" onClick={()=>{const v=p.variants[0];act('/api/admin/products/'+p.id,{method:'PUT',body:JSON.stringify({name:p.name,category:p.category,icon:p.icon||'☕',variantName:v?.name||'Стандарт',price:v?.price||0,quick:p.quick,active:true,variantId:v?.id})})}}>Вернуть</button>}</div></>}</article>)}</>}
 {section==='analytics'&&<section className="admin-section"><div className="title-row"><div><small>Продажи за выбранный день</small><h1>Аналитика</h1></div><button className="icon-button" onClick={load}><RefreshCw/></button></div><label>Дата<input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label><div className="hero"><span>Выручка</span><b>{money(analytics?.revenue)}</b><small>{analytics?.ordersCount||0} заказов за день</small></div><div className="stats"><div><span>Наличные</span><b>{money(analytics?.cash)}</b></div><div><span>Карта</span><b>{money(analytics?.card)}</b></div><div><span>Средний чек</span><b>{money(analytics?.ordersCount?(analytics.revenue/analytics.ordersCount):0)}</b></div></div><h2 className="section-title">Проданные позиции</h2><section className="chart-card">{analytics?.positions.length?analytics.positions.map(p=><div className="admin-position-row" key={p.name}><span>{p.name}</span><small>{p.quantity} шт.</small></div>):<p className="empty-state">За выбранную дату продаж нет</p>}</section></section>}
 {section==='settings'&&<section className="admin-section"><h1>Настройки</h1><button className="admin-entry" onClick={onBarista}><span><Coffee/><b>Режим бариста</b><small>Создавать обычные заказы</small></span><ArrowRight/></button><p>Список администраторов задаётся переменными ADMIN_TELEGRAM_IDS или ADMIN_TELEGRAM_ID1, ADMIN_TELEGRAM_ID2 и т.д.</p></section>}
 </main><nav><button className={section==='dashboard'?'active':''} onClick={()=>setSection('dashboard')}><Wallet/>Главная</button><button className={section==='orders'?'active':''} onClick={()=>setSection('orders')}><ShoppingBag/>Заказы</button><button className={section==='shifts'?'active':''} onClick={()=>setSection('shifts')}><Clock/>Смены</button><button className={section==='catalog'?'active':''} onClick={()=>setSection('catalog')}><Package/>Меню</button><button className={section==='analytics'?'active':''} onClick={()=>setSection('analytics')}><BarChart3/>Аналитика</button><button className={section==='settings'?'active':''} onClick={()=>setSection('settings')}><MoreHorizontal/>Ещё</button></nav></div>;
}
