using Microsoft.EntityFrameworkCore;

namespace CoffeeControl.Api;
public sealed class AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
{
 public DbSet<User> Users => Set<User>(); public DbSet<Shift> Shifts => Set<Shift>(); public DbSet<ProductCategory> Categories => Set<ProductCategory>(); public DbSet<Product> Products => Set<Product>(); public DbSet<ProductVariant> Variants => Set<ProductVariant>(); public DbSet<Order> Orders => Set<Order>(); public DbSet<OrderItem> OrderItems => Set<OrderItem>(); public DbSet<Payment> Payments => Set<Payment>(); public DbSet<WriteOff> WriteOffs => Set<WriteOff>();
 protected override void OnModelCreating(ModelBuilder b) { b.Entity<User>().HasIndex(x=>x.TelegramId).IsUnique(); b.Entity<Order>().HasIndex(x=>x.RequestId).IsUnique(); b.Entity<Order>().HasIndex(x=>x.Number).IsUnique(); b.Entity<Shift>().HasIndex(x=>new{x.UserId,x.BusinessDate}); b.Entity<Shift>().Property(x=>x.OpeningCash).HasPrecision(12,2); b.Entity<Shift>().Property(x=>x.ExpectedClosingCash).HasPrecision(12,2); b.Entity<Order>().Property(x=>x.TotalAmount).HasPrecision(12,2); b.Entity<ProductVariant>().Property(x=>x.Price).HasPrecision(12,2); b.Entity<Payment>().Property(x=>x.Amount).HasPrecision(12,2); b.Entity<OrderItem>().Property(x=>x.BasePrice).HasPrecision(12,2); b.Entity<OrderItem>().Property(x=>x.UnitPrice).HasPrecision(12,2); b.Entity<OrderItem>().Property(x=>x.TotalPrice).HasPrecision(12,2); b.Entity<OrderItemModifier>().Property(x=>x.PriceAdjustmentSnapshot).HasPrecision(12,2); }
}

public static class DbSeeder { public static async Task SeedAsync(AppDbContext db, CancellationToken ct) { if(await db.Categories.AnyAsync(ct)) return; var names=new[]{("Кофе","☕"),("Холодные напитки","🧊"),("Чай","🍵"),("Еда","🥐"),("Десерты","🍰")}; var cats=names.Select((x,i)=>new ProductCategory{Name=x.Item1,Icon=x.Item2,SortOrder=i}).ToArray(); db.Categories.AddRange(cats); var products=new[]{("Эспрессо",cats[0],60m),("Американо",cats[0],65m),("Капучино",cats[0],85m),("Латте",cats[0],90m),("Флэт уайт",cats[0],95m),("Раф",cats[0],110m),("Чизкейк",cats[4],120m)}.Select((x,i)=>new Product{Name=x.Item1,Category=x.Item2,IsQuickOrder=true,SortOrder=i,Variants=[new ProductVariant{Name="Стандарт",Price=x.Item3,IsDefault=true}]}).ToArray(); db.Products.AddRange(products); await db.SaveChangesAsync(ct); } }
