namespace CoffeeControl.Api;

public enum Role { Barista, Admin }
public enum ShiftStatus { Open, Closed }
public enum OrderStatus { Draft, Completed, Cancelled, Refunded }
public enum PaymentMethod { Cash, Card }

public sealed class User { public Guid Id { get; set; } = Guid.NewGuid(); public long TelegramId { get; set; } public string? Username { get; set; } public string FirstName { get; set; } = "Бариста"; public string? LastName { get; set; } public Role Role { get; set; } = Role.Barista; public bool IsActive { get; set; } = true; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime? LastLoginAt { get; set; } }
public sealed class Shift { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public User User { get; set; } = null!; public DateOnly BusinessDate { get; set; } public DateTime OpenedAt { get; set; } = DateTime.UtcNow; public DateTime? ClosedAt { get; set; } public decimal OpeningCash { get; set; } public decimal ExpectedClosingCash { get; set; } public decimal? ActualClosingCash { get; set; } public decimal? CashDifference { get; set; } public string? Comment { get; set; } public ShiftStatus Status { get; set; } = ShiftStatus.Open; public List<Order> Orders { get; set; } = []; public List<WriteOff> WriteOffs { get; set; } = []; }
public sealed class ProductCategory { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = ""; public string? Icon { get; set; } public int SortOrder { get; set; } public bool IsActive { get; set; } = true; public List<Product> Products { get; set; } = []; }
public sealed class Product { public Guid Id { get; set; } = Guid.NewGuid(); public Guid CategoryId { get; set; } public ProductCategory Category { get; set; } = null!; public string Name { get; set; } = ""; public string? Description { get; set; } public bool IsActive { get; set; } = true; public bool IsQuickOrder { get; set; } public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public List<ProductVariant> Variants { get; set; } = []; }
public sealed class ProductVariant { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ProductId { get; set; } public Product Product { get; set; } = null!; public string Name { get; set; } = ""; public int? VolumeMl { get; set; } public decimal Price { get; set; } public bool IsDefault { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Order { public Guid Id { get; set; } = Guid.NewGuid(); public long Number { get; set; } public Guid ShiftId { get; set; } public Shift Shift { get; set; } = null!; public Guid UserId { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; public DateTime? CancelledAt { get; set; } public string? CancellationReason { get; set; } public OrderStatus Status { get; set; } = OrderStatus.Completed; public decimal TotalAmount { get; set; } public string? Comment { get; set; } public string RequestId { get; set; } = ""; public List<OrderItem> Items { get; set; } = []; public List<Payment> Payments { get; set; } = []; }
public sealed class OrderItem { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrderId { get; set; } public Order Order { get; set; } = null!; public Guid ProductId { get; set; } public Guid ProductVariantId { get; set; } public string ProductNameSnapshot { get; set; } = ""; public string VariantNameSnapshot { get; set; } = ""; public decimal BasePrice { get; set; } public int Quantity { get; set; } public int CoffeePortions { get; set; } public int DecafPackets { get; set; } public decimal UnitPrice { get; set; } public decimal TotalPrice { get; set; } public List<OrderItemModifier> Modifiers { get; set; } = []; }
public sealed class OrderItemModifier { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrderItemId { get; set; } public string ModifierNameSnapshot { get; set; } = ""; public decimal PriceAdjustmentSnapshot { get; set; } public int Quantity { get; set; } }
public sealed class Payment { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrderId { get; set; } public Order Order { get; set; } = null!; public PaymentMethod PaymentMethod { get; set; } public decimal Amount { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public sealed class WriteOff { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ShiftId { get; set; } public Guid UserId { get; set; } public decimal Quantity { get; set; } public decimal? EstimatedAmount { get; set; } public string Reason { get; set; } = ""; public string? Comment { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
