using System.Net; using System.Security.Cryptography; using System.Text; using System.Text.Json; using Microsoft.EntityFrameworkCore;
namespace CoffeeControl.Api;
public sealed class TelegramAuth(IConfiguration config)
{ public async Task<User?> AuthenticateAsync(HttpRequest request, AppDbContext db, CancellationToken ct) { var init=request.Headers["X-Telegram-Init-Data"].FirstOrDefault(); var token=config["TELEGRAM_BOT_TOKEN"]; if(string.IsNullOrWhiteSpace(init)) { if(string.Equals(config["ASPNETCORE_ENVIRONMENT"],"Development",StringComparison.OrdinalIgnoreCase)) return await GetOrCreateAsync(db,999999,"dev","Разработчик",null,ct); return null; } if(string.IsNullOrWhiteSpace(token)) return null;
   Dictionary<string,string> parts; try { parts=init.Split('&',StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Split('=',2)).Where(x=>x.Length==2).ToDictionary(x=>WebUtility.UrlDecode(x[0]),x=>WebUtility.UrlDecode(x[1])); } catch(ArgumentException) { return null; }
   var now=DateTimeOffset.UtcNow.ToUnixTimeSeconds(); if(!parts.TryGetValue("hash",out var hash)||!parts.TryGetValue("auth_date",out var stamp)||!long.TryParse(stamp,out var unix)||unix>now+60||now-unix>86400)return null; var check=string.Join('\n',parts.Where(x=>x.Key!="hash").OrderBy(x=>x.Key).Select(x=>$"{x.Key}={x.Value}")); using var h= new HMACSHA256(Encoding.UTF8.GetBytes("WebAppData")); var secret=h.ComputeHash(Encoding.UTF8.GetBytes(token)); var expected=Convert.ToHexString(new HMACSHA256(secret).ComputeHash(Encoding.UTF8.GetBytes(check))).ToLowerInvariant(); if(hash.Length!=expected.Length||!CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(expected),Encoding.UTF8.GetBytes(hash.ToLowerInvariant())))return null; if(!parts.TryGetValue("user",out var json))return null; try { using var doc=JsonDocument.Parse(json); var u=doc.RootElement; return await GetOrCreateAsync(db,u.GetProperty("id").GetInt64(),u.TryGetProperty("username",out var un)?un.GetString():null,u.TryGetProperty("first_name",out var fn)?fn.GetString()??"Бариста":"Бариста",null,ct); } catch(JsonException) { return null; } catch(KeyNotFoundException) { return null; } }
 public async Task<User?> AuthorizeContactAsync(AppDbContext db, long id, string? username, string first, string phone, CancellationToken ct) => IsAllowed(id, phone) ? await GetOrCreateAsync(db, id, username, first, phone, ct, true) : null;
 private IEnumerable<string> AccessValues() => config.AsEnumerable().Where(x => x.Key.Equals("ADMIN_TELEGRAM_ID", StringComparison.OrdinalIgnoreCase) || x.Key.Equals("ADMIN_TELEGRAM_IDS", StringComparison.OrdinalIgnoreCase) || (x.Key.StartsWith("ADMIN_TELEGRAM_ID", StringComparison.OrdinalIgnoreCase) && x.Key["ADMIN_TELEGRAM_ID".Length..].All(char.IsDigit)) || x.Key.Equals("ADMIN_TELEGRAM_HEAD", StringComparison.OrdinalIgnoreCase)).SelectMany(x => (x.Value ?? "").Split(',', ';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries));
 private static string Digits(string value) => new(value.Where(char.IsDigit).ToArray());
 private bool Matches(string? configured, long id, string? phone) => !string.IsNullOrWhiteSpace(configured) && (long.TryParse(configured.Trim(), out var value) && value == id || Digits(configured) == Digits(phone ?? ""));
 private bool IsAllowed(long id, string? phone) => AccessValues().Any(x => Matches(x, id, phone));
 private bool IsConfiguredHead(long id, string? phone) => Matches(config["ADMIN_TELEGRAM_HEAD"], id, phone);
 private async Task<User?> GetOrCreateAsync(AppDbContext db,long id,string? username,string first,string? phone,CancellationToken ct,bool contactVerified=false){var u=await db.Users.SingleOrDefaultAsync(x=>x.TelegramId==id,ct);if(!contactVerified && !IsAllowed(id, u?.Phone))return null;if(u is null){u=new User{TelegramId=id,Phone=phone,Username=username,FirstName=first,Role=IsConfiguredHead(id,phone)?Role.Admin:Role.Barista};db.Users.Add(u);}else{if(!u.IsActive)return null;u.LastLoginAt=DateTime.UtcNow;u.Phone=phone??u.Phone;u.Username=username;u.FirstName=first;u.Role=IsConfiguredHead(id,u.Phone)?Role.Admin:Role.Barista;}await db.SaveChangesAsync(ct);return u;}
}
